name: WorldData
on: push

jobs:
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Unit Tests
        run: |
          mvn -Dtest=com.napier.group21.DatabaseConnectionTest test --no-transfer-progress
          mvn -Dtest=com.napier.group21.ReportGeneratorTest test --no-transfer-progress

  IntegrationTests:
    name: Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Database Image
        run: |
          docker build -t database ./db 
          docker run --name db -dp 33060:3306 database

      - name: Run Integration Tests
        run: |
          mvn -Dtest=com.napier.group21.AppIntegrationTest test --no-transfer-progress

      - name: Destroy Docker Image
        run: |
          docker stop employees
          docker rm employees
          docker image rm database        

  build:
    name: Build JAR with Maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Package with Maven
        run: mvn clean package -DskipTests --no-transfer-progress

      - name: Run Docker Compose
        run: docker compose up --abort-on-container-exit

      - name: View Logs
        run: docker logs worldstatistics-app-1