name: WorldData
on: push

jobs:
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Unit Tests
        run: |
          mvn -Dtest=com.napier.group21.DatabaseConnectionTest test --no-transfer-progress
          mvn -Dtest=com.napier.group21.ReportGeneratorTest test --no-transfer-progress

      - name: CodeCov
        uses: codecov/codecov-action@v5
        with:
          directory: ./target/site/jacoco

  IntegrationTests:
    name: Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Database Image
        run: |
          docker build -t database ./db 
          docker run --name db -dp 33060:3306 database

      - name: Run Integration Tests
        run: |
          mvn -Dtest=com.napier.group21.AppIntegrationTest test --no-transfer-progress

      - name: Destroy Database Image
        run: |
          docker stop db
          docker rm db
          docker image rm database        

      - name: CodeCov
        uses: codecov/codecov-action@v5
        with:
          directory: ./target/site/jacoco

  build:
    name: Build JAR with Maven and Deploy Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Package with Maven
        run: mvn clean package -DskipTests --no-transfer-progress

      - name: Run with Docker Compose
        run: docker compose up --abort-on-container-exit

      - name: "Deploy Release"
        if: success() && github.ref == 'refs/heads/release' # Only Deploy is push is to Release Branch
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: ""
          files: |
            ./target/*.jar
          

      - name: View Logs
        run: docker logs worldstatistics-app-1

